
install.packages("dplyr")
install.packages("readr")
install.packages("tidyr")
install.packages("RCurl")
install.packages("calendar")
install.packages("jsonlite")
install.packages("tidyverse")
install.packages("readr")
install.packages("caret")
install.packages("xgboost")
install.packages("tidyverse")
install.packages("xgboost")
install.packages("bigrquery")